[workspace]
resolver = "3"
members = [
    "crates/macros",
    "crates/parser",
    "crates/box",
    "crates/pretty_text",
    "demo",
    "examples",
]

[workspace.dependencies]
winnow = "0.7.11"
rand = "0.9"
thiserror = "2.0"
